from typing import List

from pydantic import BaseModel, Field

class NewsObject(BaseModel):
    title: str = Field(description="Title of the news.")
    url: str = Field(description="URL of the source of the news")
    description: str = Field(description="Short description of the news.")
    time: str = Field(description="Date and time of news")
    source: str = Field(description="Name of the source platform")
    will_it_directly_impact_any_stock: bool = Field(description="Weather stock will directly impact any indian stock or not.")
    directly_mentioned_companies_in_news: tuple = Field(description="List of name of companies which are directly mentioned in the news"),
    how_will_it_impact: tuple = Field(description="Categorical variables with values like `Positive`, `Natural` or `Negative`"),
    reason: str = Field(description="Reason which contains your thoughts for analysis generated by you.")
    
class NewsList(BaseModel):
    news: List[NewsObject]